#!/usr/bin/env npx tsx
/**
 * FPL Mobile-Assisted Auth (OAuth2 Authorization Code + PKCE)
 *
 * The box starts the flow, you finish it on your phone, the box takes it from
 * there. No password is ever stored on the box and no browser runs on the box.
 *
 *   1. Box generates a PKCE challenge and prints an authorize URL (+ QR code).
 *   2. You open it on your phone and log in to your Premier League account.
 *   3. You land on a blank 404 page whose URL contains ?code=...
 *   4. You paste that URL back into the box.
 *   5. Box exchanges the code for an access token AND a refresh token.
 *
 * Because we request the `offline_access` scope, step 1-4 is a rare event:
 * afterwards the box refreshes silently with `--refresh` (no phone, no browser,
 * no password), which is what cron / the MCP server should call.
 *
 * Usage:
 *   npm run auth            # mobile-assisted login (interactive, one-off)
 *   npm run auth:refresh    # silent refresh using the stored refresh token
 *
 * Why this design (all verified against the live auth server):
 *   - The device-code grant is NOT enabled for the FPL client
 *     ("Client is missing required grant type: DEVICE_CODE"), so RFC 8628 is out.
 *   - The client only accepts redirect URIs under https://fantasy.premierleague.com/*
 *     (anything else -> "Redirect URI mismatch"), so the box cannot host the
 *     callback itself. Hence the paste-back step.
 *   - We redirect to /static/oauth-callback, which the FPL CDN serves as a plain
 *     nginx 404 with no JavaScript. The SPA never boots, so nothing consumes or
 *     strips the ?code= before you can copy it. (Redirecting to / would hand the
 *     code to the FPL app itself, which would race us for it.)
 *   - The token endpoint accepts the FPL client as a public client with no
 *     secret, so the box can complete the exchange on its own.
 */

import { writeFileSync, readFileSync, existsSync, mkdirSync, rmSync } from "fs";
import { homedir } from "os";
import { join } from "path";
import { createInterface } from "readline";
import { randomBytes, createHash } from "crypto";

const CLIENT_ID = "bfcbaf69-aade-4c1b-8f00-c1cb8a193030";
const AUTHORIZE_URL = "https://account.premierleague.com/as/authorize";
const TOKEN_URL = "https://account.premierleague.com/as/token";
const SCOPE = "openid profile email offline_access";

// Must live under https://fantasy.premierleague.com/* (client restriction), and
// must be a path the CDN 404s so no SPA JavaScript runs on the landing page.
const REDIRECT_URI = "https://fantasy.premierleague.com/static/oauth-callback";

const FPL_DIR = join(homedir(), ".fpl");
const SECRETS_FILE = join(FPL_DIR, "secrets.env");

// ---------------------------------------------------------------- secrets io

interface Secrets {
  token: string | null;
  refreshToken: string | null;
  managerId: string | null;
  braveApiKey: string | null;
}

function readSecrets(): Secrets {
  const empty: Secrets = { token: null, refreshToken: null, managerId: null, braveApiKey: null };
  if (!existsSync(SECRETS_FILE)) return empty;
  try {
    const content = readFileSync(SECRETS_FILE, "utf-8");
    const grab = (key: string) => content.match(new RegExp(`export ${key}="([^"]+)"`))?.[1] ?? null;
    return {
      token: grab("FPL_X_API_AUTH"),
      refreshToken: grab("FPL_REFRESH_TOKEN"),
      managerId: grab("FPL_MANAGER_ID"),
      braveApiKey: grab("BRAVE_SEARCH_API_KEY"),
    };
  } catch {
    return empty;
  }
}

function writeSecrets(s: Secrets) {
  if (!existsSync(FPL_DIR)) mkdirSync(FPL_DIR, { recursive: true });
  let content =
    "# FPL Secrets (auto-generated by mobile-auth.ts)\n" +
    "# Access token expires often; refresh silently with: npm run auth:refresh\n" +
    "# Full re-login (phone required): npm run auth\n";
  if (s.token) content += `export FPL_X_API_AUTH="${s.token}"\n`;
  if (s.refreshToken) content += `export FPL_REFRESH_TOKEN="${s.refreshToken}"\n`;
  if (s.managerId) content += `export FPL_MANAGER_ID="${s.managerId}"\n`;
  if (s.braveApiKey) content += `export BRAVE_SEARCH_API_KEY="${s.braveApiKey}"\n`;
  writeFileSync(SECRETS_FILE, content, { mode: 0o600 });
}

// ------------------------------------------------------------------- tokens

function decodeJwtPayload(raw: string): Record<string, unknown> | null {
  try {
    const tok = raw.startsWith("Bearer ") ? raw.slice(7) : raw;
    const parts = tok.split(".");
    if (parts.length < 2) return null;
    return JSON.parse(Buffer.from(parts[1], "base64").toString()) as Record<string, unknown>;
  } catch {
    return null;
  }
}

function getTokenExpiry(raw: string): Date | null {
  const payload = decodeJwtPayload(raw);
  const exp = payload?.exp;
  return typeof exp === "number" ? new Date(exp * 1000) : null;
}

// Reject the short-lived "flow" JWTs the DaVinci provider hands out while
// driving its login state machine — the FPL resource server signs with a
// different JWKS and rejects them with "Unable to find a signing key".
function isUserAccessToken(raw: string): boolean {
  const payload = decodeJwtPayload(raw);
  if (!payload) return false;
  if (payload.usage === "startSpecificFlowOrPolicyNonUserContext") return false;
  if (payload.sub && payload.aud && payload.sub === payload.aud) return false;
  return true;
}

function describeExpiry(raw: string): string {
  const expiry = getTokenExpiry(raw);
  if (!expiry) return "unknown expiry";
  const ms = expiry.getTime() - Date.now();
  if (ms <= 0) return "already expired";
  const h = Math.floor(ms / 3_600_000);
  const m = Math.floor((ms % 3_600_000) / 60_000);
  return `expires in ${h}h ${m}m (${expiry.toISOString()})`;
}

interface TokenResponse {
  access_token?: string;
  refresh_token?: string;
  token_type?: string;
  expires_in?: number;
  error?: string;
  error_description?: string;
}

async function postToken(params: Record<string, string>): Promise<TokenResponse> {
  const body = new URLSearchParams(params);
  const response = await fetch(TOKEN_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      "User-Agent": "Mozilla/5.0",
    },
    body: body.toString(),
  });
  const text = await response.text();
  try {
    return JSON.parse(text) as TokenResponse;
  } catch {
    return { error: "invalid_response", error_description: text.slice(0, 300) };
  }
}

async function fetchManagerId(bearer: string): Promise<string | null> {
  try {
    const response = await fetch("https://fantasy.premierleague.com/api/me/", {
      headers: { "X-Api-Authorization": bearer },
    });
    if (!response.ok) return null;
    const data = (await response.json()) as { player?: { entry?: number } };
    return data.player?.entry?.toString() ?? null;
  } catch {
    return null;
  }
}

/** Persist a token response. Returns the bearer string that was saved. */
async function persistTokens(tokens: TokenResponse, previous: Secrets): Promise<string> {
  const bearer = `Bearer ${tokens.access_token}`;

  if (!isUserAccessToken(bearer)) {
    console.error("\n❌ The auth server returned a token that the FPL API will reject");
    console.error("   (it looks like an OAuth flow-bootstrap JWT, not a user access token).");
    process.exit(1);
  }

  // Refresh tokens usually rotate; keep the old one only if none came back.
  const refreshToken = tokens.refresh_token ?? previous.refreshToken;
  const managerId = previous.managerId ?? (await fetchManagerId(bearer));

  writeSecrets({
    token: bearer,
    refreshToken,
    managerId,
    braveApiKey: previous.braveApiKey,
  });

  console.log(`\n✅ Access token saved — ${describeExpiry(bearer)}`);
  if (refreshToken) {
    console.log("✅ Refresh token saved — future refreshes need no phone and no password:");
    console.log("      npm --prefix fpl-mcp-server run auth:refresh");
  } else {
    console.warn("⚠️  No refresh token returned. You will need to redo the phone login next time.");
  }
  if (managerId) console.log(`✅ Manager ID: ${managerId}`);
  console.log(`\n📁 Saved to ${SECRETS_FILE}`);
  console.log("   Load it into your shell with:  source ~/.fpl/secrets.env");
  console.log("   Then restart Claude Code so the MCP server picks up the new token.");

  return bearer;
}

// -------------------------------------------------------------------- input

function prompt(question: string): Promise<string> {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

/**
 * Accept whatever the user manages to paste from their phone: the whole
 * redirect URL, a bare query string, or just the code itself.
 */
function extractCodeAndState(pasted: string): { code: string; state: string | null } | null {
  const input = pasted.trim().replace(/^["']|["']$/g, "");
  if (!input) return null;

  const fromParams = (params: URLSearchParams) => {
    const error = params.get("error");
    if (error) {
      console.error(`\n❌ The auth server returned an error: ${error}`);
      const description = params.get("error_description");
      if (description) console.error(`   ${description}`);
      process.exit(1);
    }
    const code = params.get("code");
    return code ? { code, state: params.get("state") } : null;
  };

  if (input.includes("?") || input.includes("&") || input.includes("=")) {
    try {
      return fromParams(new URL(input).searchParams);
    } catch {
      return fromParams(new URLSearchParams(input.replace(/^[^?]*\?/, "")));
    }
  }

  // Looks like a bare code.
  return { code: input, state: null };
}

interface QrModule {
  generate: (text: string, opts: { small: boolean }) => void;
  setErrorLevel: (level: "L" | "M" | "Q" | "H") => void;
}

async function renderQr(text: string) {
  let qr: QrModule;
  try {
    const imported = (await import("qrcode-terminal")) as unknown as { default?: QrModule } & QrModule;
    qr = imported.default ?? imported;
  } catch {
    console.log("\n   (run `npm install` for a scannable QR code — copy the URL above meanwhile)");
    return;
  }

  try {
    // Must be set before generate(): without it the internal errorCorrectLevel
    // is undefined and sizing fails with "bad rs block @ typeNumber:1".
    // 'L' also keeps this long URL to the smallest QR that still scans.
    qr.setErrorLevel("L");
    console.log("\n📱 Scan this with your phone camera:\n");
    qr.generate(text, { small: true });
  } catch (error) {
    console.log(`\n   (could not render QR: ${(error as Error).message} — use the URL above)`);
  }
}

// ------------------------------------------------------- pending flow state

// --start and --finish run as two separate processes (so an agent can print the
// link, let you go to your phone, and complete the exchange in a later turn).
// The PKCE verifier has to survive in between, so it is parked here.
const PENDING_FILE = join(FPL_DIR, "pending-auth.json");
const PENDING_TTL_MS = 30 * 60 * 1000;

interface PendingAuth {
  codeVerifier: string;
  state: string;
  createdAt: number;
}

function writePending(pending: PendingAuth) {
  if (!existsSync(FPL_DIR)) mkdirSync(FPL_DIR, { recursive: true });
  writeFileSync(PENDING_FILE, JSON.stringify(pending, null, 2), { mode: 0o600 });
}

function readPending(): PendingAuth | null {
  if (!existsSync(PENDING_FILE)) return null;
  try {
    return JSON.parse(readFileSync(PENDING_FILE, "utf-8")) as PendingAuth;
  } catch {
    return null;
  }
}

function clearPending() {
  try {
    if (existsSync(PENDING_FILE)) rmSync(PENDING_FILE);
  } catch {
    // best effort
  }
}

// ------------------------------------------------------------------- flows

/** Build the authorize URL and show it. Returns the PKCE state to complete with. */
async function beginLogin(): Promise<PendingAuth> {
  const codeVerifier = randomBytes(32).toString("base64url");
  const codeChallenge = createHash("sha256").update(codeVerifier).digest("base64url");
  const state = randomBytes(16).toString("hex");

  const authorizeUrl = new URL(AUTHORIZE_URL);
  authorizeUrl.searchParams.set("client_id", CLIENT_ID);
  authorizeUrl.searchParams.set("redirect_uri", REDIRECT_URI);
  authorizeUrl.searchParams.set("response_type", "code");
  authorizeUrl.searchParams.set("scope", SCOPE);
  authorizeUrl.searchParams.set("state", state);
  authorizeUrl.searchParams.set("code_challenge", codeChallenge);
  authorizeUrl.searchParams.set("code_challenge_method", "S256");

  console.log("🔐 FPL Mobile Login");
  console.log("===================\n");
  console.log("Open this on your phone and log in to your Premier League account:\n");
  console.log(authorizeUrl.toString());

  await renderQr(authorizeUrl.toString());

  console.log("\n─────────────────────────────────────────────────────────────");
  console.log("After you log in, your phone lands on a blank '404 Not Found'");
  console.log("page. That is expected and means it worked.");
  console.log("");
  console.log("Copy the FULL URL of that 404 page from the address bar");
  console.log("(long-press the address bar → Copy).");
  console.log("It looks like:");
  console.log(`  ${REDIRECT_URI}?code=...&state=...`);
  console.log("─────────────────────────────────────────────────────────────");

  return { codeVerifier, state, createdAt: Date.now() };
}

/** Exchange a pasted URL/code against a pending PKCE state. */
async function completeLogin(pending: PendingAuth, pasted: string) {
  const previous = readSecrets();
  const parsed = extractCodeAndState(pasted);

  if (!parsed) {
    console.error("\n❌ Could not find an authorization code in what you pasted.");
    console.error("   Make sure you copied the whole URL of the 404 page.");
    process.exit(1);
  }

  if (parsed.state && parsed.state !== pending.state) {
    console.error("\n❌ State mismatch — this response does not belong to this login attempt.");
    console.error("   Start over with: npm run auth");
    process.exit(1);
  }
  if (!parsed.state) {
    console.warn("\n⚠️  No state in the pasted value, so it could not be cross-checked.");
  }

  console.log("\n🔄 Exchanging the code for tokens...");
  const tokens = await postToken({
    grant_type: "authorization_code",
    client_id: CLIENT_ID,
    code: parsed.code,
    redirect_uri: REDIRECT_URI,
    code_verifier: pending.codeVerifier,
  });

  if (!tokens.access_token) {
    console.error(`\n❌ Token exchange failed: ${tokens.error ?? "unknown error"}`);
    if (tokens.error_description) console.error(`   ${tokens.error_description}`);
    if (tokens.error === "invalid_grant") {
      console.error("\n   Authorization codes are single-use and short-lived.");
      console.error("   Re-run 'npm run auth' and paste the URL more promptly.");
    }
    process.exit(1);
  }

  await persistTokens(tokens, previous);
}

async function refresh({ force }: { force: boolean }) {
  const previous = readSecrets();

  if (!force && previous.token && isUserAccessToken(previous.token)) {
    const expiry = getTokenExpiry(previous.token);
    if (expiry && expiry.getTime() > Date.now() + 5 * 60 * 1000) {
      console.log(`✅ Token still valid — ${describeExpiry(previous.token)}`);
      return;
    }
  }

  if (!previous.refreshToken) {
    console.error("❌ No refresh token stored, so a silent refresh is not possible.");
    console.error("   Run the one-off phone login first:");
    console.error("      npm --prefix fpl-mcp-server run auth");
    process.exit(1);
  }

  console.log("🔄 Refreshing access token (no browser, no phone)...");
  const tokens = await postToken({
    grant_type: "refresh_token",
    client_id: CLIENT_ID,
    refresh_token: previous.refreshToken,
  });

  if (!tokens.access_token) {
    console.error(`\n❌ Refresh failed: ${tokens.error ?? "unknown error"}`);
    if (tokens.error_description) console.error(`   ${tokens.error_description}`);
    console.error("\n   The refresh token has probably expired or been revoked.");
    console.error("   Redo the phone login:  npm --prefix fpl-mcp-server run auth");
    process.exit(1);
  }

  await persistTokens(tokens, previous);
}

/** Interactive one-process login: show the link, wait at the prompt, exchange. */
async function login() {
  const pending = await beginLogin();
  const pasted = await prompt("\nPaste the URL (or just the code): ");
  await completeLogin(pending, pasted);
  clearPending();
}

/** Print the link and park the PKCE state for a later --finish. */
async function startLogin() {
  const pending = await beginLogin();
  writePending(pending);
  console.log("\n⏳ Waiting for you. When you have the URL, run:");
  console.log("      npm --prefix fpl-mcp-server run auth:finish -- '<pasted-url>'");
}

/** Complete a login started earlier by --start. */
async function finishLogin(pasted: string | undefined) {
  if (!pasted) {
    console.error("❌ Nothing to finish with. Pass the URL you copied:");
    console.error("   npm --prefix fpl-mcp-server run auth:finish -- '<pasted-url>'");
    process.exit(1);
  }

  const pending = readPending();
  if (!pending) {
    console.error("❌ No login in progress. Start one with:");
    console.error("   npm --prefix fpl-mcp-server run auth:start");
    process.exit(1);
  }

  if (Date.now() - pending.createdAt > PENDING_TTL_MS) {
    clearPending();
    console.error("❌ That login attempt is over 30 minutes old and has been discarded.");
    console.error("   Start a fresh one:  npm --prefix fpl-mcp-server run auth:start");
    process.exit(1);
  }

  await completeLogin(pending, pasted);
  clearPending();
}

// -------------------------------------------------------------------- entry

const args = process.argv.slice(2);
if (args.includes("--help") || args.includes("-h")) {
  console.log("Usage:");
  console.log("  npx tsx scripts/mobile-auth.ts                     interactive login (one process)");
  console.log("  npx tsx scripts/mobile-auth.ts --start             print the link, park PKCE state");
  console.log("  npx tsx scripts/mobile-auth.ts --finish '<url>'    complete a --start login");
  console.log("  npx tsx scripts/mobile-auth.ts --refresh           silent refresh via refresh token");
  console.log("  npx tsx scripts/mobile-auth.ts --refresh --force   refresh even if still valid");
  process.exit(0);
}

let run: Promise<void>;
if (args.includes("--refresh")) {
  run = refresh({ force: args.includes("--force") });
} else if (args.includes("--start")) {
  run = startLogin();
} else if (args.includes("--finish")) {
  run = finishLogin(args[args.indexOf("--finish") + 1]);
} else {
  run = login();
}

run.catch((error) => {
  console.error("❌ Unexpected error:", error);
  process.exit(1);
});
