#!/usr/bin/env npx tsx
/**
 * FPL Headless Token Refresh
 *
 * Automatically logs in to FPL using stored credentials and refreshes
 * the auth token. Designed to run on a headless server (no display needed).
 *
 * Credentials are stored in ~/.fpl/credentials.env (chmod 0600)
 *
 * First-time setup (run on any machine):
 *   npx tsx scripts/refresh-token.ts --save-credentials
 *
 * Headless refresh (cron, server, bot trigger):
 *   npx tsx scripts/refresh-token.ts
 *
 * Usage:
 *   npm run refresh-token              # headless refresh
 *   npm run refresh-token -- --save-credentials  # save credentials
 */

import { chromium } from "playwright";
import { writeFileSync, readFileSync, existsSync, mkdirSync, chmodSync } from "fs";
import { homedir } from "os";
import { join } from "path";
import { createInterface } from "readline";
import { randomBytes, createHash } from "crypto";

const FPL_URL = "https://fantasy.premierleague.com/my-team";
const FPL_DIR = join(homedir(), ".fpl");
const CREDENTIALS_FILE = join(FPL_DIR, "credentials.env");
const SECRETS_FILE = join(FPL_DIR, "secrets.env");

function prompt(question: string): Promise<string> {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

function promptPassword(question: string): Promise<string> {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => {
    // Disable echo for password input
    if (process.stdin.isTTY) {
      process.stdout.write(question);
      const stdin = process.openStdin();
      stdin.once("data", (data) => {
        rl.close();
        process.stdout.write("\n");
        resolve(data.toString().trim());
      });
    } else {
      rl.question(question, (answer) => {
        rl.close();
        resolve(answer.trim());
      });
    }
  });
}

function ensureDir() {
  if (!existsSync(FPL_DIR)) {
    mkdirSync(FPL_DIR, { recursive: true });
  }
}

function loadCredentials(): { email: string; password: string } | null {
  if (!existsSync(CREDENTIALS_FILE)) return null;

  try {
    const content = readFileSync(CREDENTIALS_FILE, "utf-8");
    const emailMatch = content.match(/^FPL_EMAIL=(.+)$/m);
    const passwordMatch = content.match(/^FPL_PASSWORD=(.+)$/m);

    if (emailMatch && passwordMatch) {
      return { email: emailMatch[1], password: passwordMatch[1] };
    }
  } catch {
    // ignore
  }
  return null;
}

async function saveCredentials() {
  console.log("🔐 Save FPL Credentials");
  console.log("========================");
  console.log("These will be stored in ~/.fpl/credentials.env (chmod 0600)\n");

  const email = await prompt("FPL email: ");
  const password = await prompt("FPL password: ");

  if (!email || !password) {
    console.error("❌ Email and password are required.");
    process.exit(1);
  }

  ensureDir();
  const content = `# FPL credentials (auto-generated by refresh-token.ts)\n# chmod 0600 - only readable by owner\nFPL_EMAIL=${email}\nFPL_PASSWORD=${password}\n`;
  writeFileSync(CREDENTIALS_FILE, content, { mode: 0o600 });
  chmodSync(CREDENTIALS_FILE, 0o600);
  console.log(`\n✅ Credentials saved to ${CREDENTIALS_FILE}`);
  console.log("You can now run 'npm run refresh-token' to refresh headlessly.");
}

function getTokenExpiry(token: string): Date | null {
  try {
    const tokenPart = token.startsWith("Bearer ") ? token.slice(7) : token;
    const payload = JSON.parse(Buffer.from(tokenPart.split(".")[1], "base64").toString());
    if (payload.exp) return new Date(payload.exp * 1000);
  } catch {
    // ignore
  }
  return null;
}

function isTokenValid(token: string): boolean {
  if (!isUserAccessToken(token)) return false;
  const expiry = getTokenExpiry(token);
  if (!expiry) return false;
  return expiry.getTime() > Date.now() + 5 * 60 * 1000;
}

// Reject tokens that aren't post-login user access tokens for the FPL API.
// The DaVinci OAuth provider hands out short-lived "flow" JWTs while driving
// the login state machine; those have usage=startSpecificFlowOrPolicyNonUserContext
// (or sub==aud, i.e. no user identity) and the FPL resource server signs them
// with a different JWKS — using one results in
// {"detail": "Unable to find a signing key that matches: ..."} 401s.
function isUserAccessToken(rawToken: string): boolean {
  try {
    const tok = rawToken.startsWith("Bearer ") ? rawToken.slice(7) : rawToken;
    const parts = tok.split(".");
    if (parts.length < 2) return false;
    const payload = JSON.parse(Buffer.from(parts[1], "base64").toString()) as {
      usage?: string;
      sub?: string;
      aud?: string;
    };
    if (payload.usage === "startSpecificFlowOrPolicyNonUserContext") return false;
    if (payload.sub && payload.aud && payload.sub === payload.aud) return false;
    return true;
  } catch {
    return false;
  }
}

// Only trust tokens seen on calls to the FPL resource server. Tokens flowing
// through account.premierleague.com / users.premierleague.com belong to the
// OAuth provider, not to the API we're authenticating against.
function isFplApiUrl(url: string): boolean {
  return url.includes("fantasy.premierleague.com/api/");
}

function loadExistingToken(): string | null {
  if (!existsSync(SECRETS_FILE)) return null;
  try {
    const content = readFileSync(SECRETS_FILE, "utf-8");
    const match = content.match(/export FPL_X_API_AUTH="([^"]+)"/);
    return match?.[1] ?? null;
  } catch {
    return null;
  }
}

function loadExistingSecrets(): { managerId: string | null; braveApiKey: string | null } {
  const result = { managerId: null as string | null, braveApiKey: null as string | null };
  if (!existsSync(SECRETS_FILE)) return result;
  try {
    const content = readFileSync(SECRETS_FILE, "utf-8");
    result.managerId = content.match(/export FPL_MANAGER_ID="([^"]+)"/)?.[1] ?? null;
    result.braveApiKey = content.match(/export BRAVE_SEARCH_API_KEY="([^"]+)"/)?.[1] ?? null;
  } catch {
    // ignore
  }
  return result;
}

function saveSecrets(token: string, managerId: string | null, braveApiKey: string | null) {
  ensureDir();
  let content = `# FPL Secrets (auto-generated by refresh-token.ts)\n# Re-run 'npm run refresh-token' when token expires\nexport FPL_X_API_AUTH="${token}"\n`;
  if (managerId) content += `export FPL_MANAGER_ID="${managerId}"\n`;
  if (braveApiKey) content += `export BRAVE_SEARCH_API_KEY="${braveApiKey}"\n`;
  writeFileSync(SECRETS_FILE, content, { mode: 0o600 });
}

async function refreshToken() {
  // Check if current token is still valid
  const existingToken = loadExistingToken();
  if (existingToken && isTokenValid(existingToken)) {
    const expiry = getTokenExpiry(existingToken)!;
    const remaining = expiry.getTime() - Date.now();
    const hours = Math.floor(remaining / (1000 * 60 * 60));
    const minutes = Math.floor((remaining % (1000 * 60 * 60)) / (1000 * 60));
    console.log(`✅ Token still valid (expires in ${hours}h ${minutes}m)`);
    process.exit(0);
  }

  // Load credentials
  const credentials = loadCredentials();
  if (!credentials) {
    console.error("❌ No credentials found. Run with --save-credentials first:");
    console.error("   npx tsx scripts/refresh-token.ts --save-credentials");
    process.exit(1);
  }

  console.log("🔄 Refreshing FPL token headlessly...");

  const browser = await chromium.launch({ headless: true });
  const context = await browser.newContext({
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
  });
  const page = await context.newPage();

  let capturedToken: string | null = null;

  // Listen for the auth token in request headers — but only on calls to the
  // FPL resource server. DaVinci sends flow-bootstrap JWTs in the same header
  // during the OAuth dance; those are the wrong tokens (they have
  // usage=startSpecificFlowOrPolicyNonUserContext and are signed by a
  // different JWKS than the FPL API trusts).
  page.on("request", (request) => {
    if (capturedToken) return;
    if (!isFplApiUrl(request.url())) return;
    const headers = request.headers();
    const authHeader = headers["x-api-authorization"] || headers["authorization"];
    if (!authHeader || !authHeader.includes("eyJ")) return;
    const candidate = authHeader.startsWith("Bearer ") ? authHeader : `Bearer ${authHeader}`;
    if (!isUserAccessToken(candidate)) return;
    capturedToken = candidate;
    console.log("   ✅ Token captured from FPL API request");
  });

  // PKCE state — required by the AS even though we let the SPA do the exchange.
  const codeVerifier = randomBytes(32).toString("base64url");
  const codeChallenge = createHash("sha256").update(codeVerifier).digest("base64url");
  const state = randomBytes(16).toString("hex");
  const CLIENT_ID = "bfcbaf69-aade-4c1b-8f00-c1cb8a193030";
  const REDIRECT_URI = "https://fantasy.premierleague.com/";

  try {
    // Navigate to FPL
    console.log("📡 Navigating to FPL...");
    await page.goto("https://fantasy.premierleague.com/", { waitUntil: "domcontentloaded", timeout: 30000 });

    let url = page.url();
    console.log(`   Current URL: ${url.substring(0, 80)}...`);

    // Build OAuth2 PKCE authorize URL and navigate directly to login.
    // This bypasses the SPA's login button which has redirect_uri issues in headless mode.
    if (!url.includes("account.premierleague.com")) {
      console.log("📝 Building OAuth2 PKCE login URL...");

      const authorizeUrl = new URL("https://account.premierleague.com/as/authorize");
      authorizeUrl.searchParams.set("client_id", CLIENT_ID);
      authorizeUrl.searchParams.set("redirect_uri", REDIRECT_URI);
      authorizeUrl.searchParams.set("response_type", "code");
      authorizeUrl.searchParams.set("scope", "openid profile email offline_access");
      authorizeUrl.searchParams.set("state", state);
      authorizeUrl.searchParams.set("code_challenge", codeChallenge);
      authorizeUrl.searchParams.set("code_challenge_method", "S256");

      console.log("   Navigating to login page...");
      await page.goto(authorizeUrl.toString(), { waitUntil: "domcontentloaded", timeout: 30000 });
      await page.waitForTimeout(2000);
      url = page.url();
      console.log(`   Now at: ${url.substring(0, 80)}...`);
    }

    // Now we should be on the OAuth login page
    if (url.includes("account.premierleague.com") || url.includes("users.premierleague.com")) {
      console.log("📝 Login page detected, filling form...");

      // Wait for the login form to render
      await page.waitForTimeout(2000);

      // Wait for any input to appear
      try {
        await page.waitForSelector('input', { timeout: 10000 });
      } catch {
        console.error("❌ No input fields found on login page.");
        console.error("   URL:", page.url());
        await browser.close();
        process.exit(1);
      }

      // Fill email - try multiple selectors
      const emailSelectors = ['input[placeholder*="mail"]', 'input[type="email"]', 'input[type="text"]', 'input[name="login"]', 'input[name="email"]', 'input[name="username"]'];
      let emailFilled = false;
      for (const sel of emailSelectors) {
        try {
          const el = page.locator(sel).first();
          if (await el.isVisible({ timeout: 1000 })) {
            await el.fill(credentials.email);
            console.log(`   Email filled via: ${sel}`);
            emailFilled = true;
            break;
          }
        } catch { continue; }
      }
      if (!emailFilled) {
        // Fallback: fill first visible input
        const firstInput = page.locator('input:visible').first();
        await firstInput.fill(credentials.email);
        console.log("   Email filled via first visible input");
      }

      // Fill password
      const passwordInput = page.locator('input[type="password"]').first();
      await passwordInput.waitFor({ timeout: 5000 });
      await passwordInput.fill(credentials.password);
      console.log("   Password filled");

      // Submit the form
      console.log("🔑 Submitting login...");
      // Try submit button first, then Enter key
      try {
        const submitBtn = page.locator('button[type="submit"], input[type="submit"]').first();
        if (await submitBtn.isVisible({ timeout: 2000 })) {
          await submitBtn.click();
        } else {
          await passwordInput.press("Enter");
        }
      } catch {
        await passwordInput.press("Enter");
      }

      // After login the SPA reloads at fantasy.premierleague.com, completes
      // its own auth handshake, and fires authenticated /api/ calls. Our
      // request listener (URL-gated to /api/, JWT-validated) snatches the
      // first user access token off one of those calls.
      console.log("🔍 Waiting for SPA to make an authenticated API call...");
      const deadline = Date.now() + 30_000;
      while (!capturedToken && Date.now() < deadline) {
        await page.waitForTimeout(250);
      }

      // Fallback: if the listener missed (e.g. the SPA cached a token from a
      // prior session and didn't re-auth in time), navigate to /my-team to
      // force fresh API calls.
      if (!capturedToken) {
        console.log("   ↳ no token yet, forcing /my-team to trigger API calls...");
        await page.goto(FPL_URL, { waitUntil: "domcontentloaded", timeout: 30000 }).catch(() => {});
        const deadline2 = Date.now() + 15_000;
        while (!capturedToken && Date.now() < deadline2) {
          await page.waitForTimeout(250);
        }
      }
    }

    await browser.close();

    if (!capturedToken) {
      console.error("❌ Failed to capture token. Login may have failed.");
      console.error("   Check your credentials with --save-credentials");
      process.exit(1);
    }

    // Get manager ID
    const existing = loadExistingSecrets();
    let managerId = existing.managerId;

    if (!managerId) {
      try {
        const meResponse = await fetch("https://fantasy.premierleague.com/api/me/", {
          headers: { "X-Api-Authorization": capturedToken },
        });
        if (meResponse.ok) {
          const meData = (await meResponse.json()) as { player?: { entry?: number } };
          managerId = meData.player?.entry?.toString() ?? null;
        }
      } catch {
        // ignore
      }
    }

    // Save
    saveSecrets(capturedToken, managerId, existing.braveApiKey);

    const expiry = getTokenExpiry(capturedToken);
    console.log(`\n✅ Token refreshed successfully!`);
    if (expiry) {
      const remaining = expiry.getTime() - Date.now();
      const hours = Math.floor(remaining / (1000 * 60 * 60));
      const minutes = Math.floor((remaining % (1000 * 60 * 60)) / (1000 * 60));
      console.log(`   Expires: ${expiry.toISOString()} (${hours}h ${minutes}m)`);
    }
    if (managerId) console.log(`   Manager ID: ${managerId}`);
    console.log(`   Saved to: ${SECRETS_FILE}`);
  } catch (error) {
    await browser.close();
    console.error("❌ Error during token refresh:", error);
    process.exit(1);
  }
}

// Main
const args = process.argv.slice(2);
if (args.includes("--save-credentials")) {
  saveCredentials();
} else {
  refreshToken();
}
