#!/usr/bin/env npx tsx
/**
 * FPL Setup
 *
 * Opens a browser window for you to log in to FPL, then captures:
 * - X-Api-Authorization token
 * - Your manager ID
 *
 * Saves both to ~/.fpl/secrets.env
 *
 * Usage:
 *   npx tsx scripts/setup.ts
 *   # or
 *   npm run setup
 */

import { chromium } from "playwright";
import { writeFileSync, readFileSync, existsSync, mkdirSync } from "fs";
import { homedir } from "os";
import { join, dirname } from "path";

const FPL_URL = "https://fantasy.premierleague.com/my-team";
const FPL_SECRETS_DIR = join(homedir(), ".fpl");
const FPL_SECRETS_FILE = join(FPL_SECRETS_DIR, "secrets.env");

async function main() {
  console.log("🔐 FPL Setup");
  console.log("============\n");
  console.log("A browser window will open. Please log in to FPL.");
  console.log("Your token and manager ID will be captured automatically after login.\n");

  const browser = await chromium.launch({
    headless: false, // Show the browser so user can log in
  });

  const context = await browser.newContext();
  const page = await context.newPage();

  let capturedToken: string | null = null;

  // Listen for network requests to capture the auth header
  page.on("request", (request) => {
    const headers = request.headers();
    const authHeader = headers["x-api-authorization"];

    if (authHeader && authHeader.startsWith("Bearer ") && !capturedToken) {
      capturedToken = authHeader;
      console.log("\n✅ Token captured!");
    }
  });

  // Also check response headers in case it's set there
  page.on("response", async (response) => {
    const url = response.url();
    if (url.includes("fantasy.premierleague.com") && !capturedToken) {
      const request = response.request();
      const authHeader = request.headers()["x-api-authorization"];
      if (authHeader && authHeader.startsWith("Bearer ")) {
        capturedToken = authHeader;
        console.log("\n✅ Token captured from response!");
      }
    }
  });

  try {
    await page.goto(FPL_URL);

    // Wait for either login to complete or timeout
    console.log("⏳ Waiting for you to log in...\n");

    // Poll until we have the token or user closes browser
    const maxWaitMs = 5 * 60 * 1000; // 5 minutes
    const startTime = Date.now();

    while (!capturedToken && Date.now() - startTime < maxWaitMs) {
      await page.waitForTimeout(1000);

      // Check if we're on the my-team page (logged in)
      const url = page.url();
      if (url.includes("/my-team") && !url.includes("login")) {
        // Trigger a request to capture the token
        try {
          await page.reload({ waitUntil: "networkidle" });
        } catch {
          // Page might have been closed
          break;
        }
      }
    }

    if (!capturedToken) {
      console.log("❌ No token captured. Make sure you logged in successfully.");
      await browser.close();
      process.exit(1);
    }

    await browser.close();

    // Fetch manager ID using the captured token
    console.log("\n📡 Fetching manager ID...");
    let managerId: number | null = null;
    try {
      const meResponse = await fetch("https://fantasy.premierleague.com/api/me/", {
        headers: {
          "X-Api-Authorization": capturedToken,
        },
      });

      if (meResponse.ok) {
        const meData = await meResponse.json() as { player?: { entry?: number } };
        managerId = meData.player?.entry ?? null;
        if (managerId) {
          console.log(`✅ Manager ID: ${managerId}`);
        } else {
          console.log("⚠️  Could not find manager ID in response");
        }
      } else {
        console.log(`⚠️  Failed to fetch manager info: ${meResponse.status}`);
      }
    } catch (err) {
      console.log("⚠️  Error fetching manager ID:", err);
    }

    // Save to secrets file
    console.log("\n📝 Saving to ~/.fpl/secrets.env...");
    saveSecrets(capturedToken, managerId);

    console.log("\n✨ Done! Run 'source ~/.zshrc' or restart your terminal.");
    console.log("\nToken preview: " + capturedToken.substring(0, 50) + "...");

    // Parse and show expiry
    try {
      const payload = JSON.parse(Buffer.from(capturedToken.split(".")[1], "base64").toString());
      if (payload.exp) {
        const expiry = new Date(payload.exp * 1000);
        console.log(`Token expires: ${expiry.toLocaleString()}`);
      }
    } catch {
      // Ignore parsing errors
    }

  } catch (error) {
    console.error("Error:", error);
    await browser.close();
    process.exit(1);
  }
}

function saveSecrets(token: string, managerId: number | null) {
  // Create ~/.fpl directory if it doesn't exist
  if (!existsSync(FPL_SECRETS_DIR)) {
    mkdirSync(FPL_SECRETS_DIR, { recursive: true });
    console.log(`Created ${FPL_SECRETS_DIR}/`);
  }

  // Build secrets content
  let content = `# FPL Secrets (auto-generated by npm run setup)
# Re-run 'npm run setup' when token expires
export FPL_X_API_AUTH="${token}"
`;

  if (managerId) {
    content += `export FPL_MANAGER_ID="${managerId}"
`;
  }

  writeFileSync(FPL_SECRETS_FILE, content, { mode: 0o600 }); // Read/write only for owner
  console.log(`Saved secrets to ${FPL_SECRETS_FILE}`);
}

main();
